trigger:
- master

pool:
  name: default

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: '**/*.csproj'
#    arguments: '--configuration $(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '**/*.UnitTests.csproj'
#    arguments: '--no-build --configuration $(buildConfiguration)'
#    testRunTitle: '$(Build.DefinitionName)_$(Build.BuildNumber)'

#- task: CopyFiles@2
#  inputs:
#    Contents: 'SSNApi/bin/Release/net?.0/*.*'
#    TargetFolder: '$(Build.ArtifactStagingDirectory)'
#    flattenFolders: false

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)/SSNApi/bin/Release'
#    ArtifactName: 'Artifacts'
#    publishLocation: 'Container'

- task: Docker@0
  inputs:
    containerregistrytype: 'Container Registry'
    action: 'Build an image'
    dockerFile: './SSNApi/Dockerfile'
    buildArguments: '--force-rm .'
    defaultContext: false
    imageName: 'registry.local:5000/$(Build.Repository.Name):$(Build.BuildId)'
    qualifyImageName: false
    includeLatestTag: true
- task: Docker@1
  inputs:
    containerregistrytype: 'Container Registry'
    command: 'Push an image'
    imageName: 'registry.local:5000/$(Build.Repository.Name):$(Build.BuildId)'
    qualifyImageName: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'SSNApi/deploy/ssnapi'
    ArtifactName: 'Artifacts'
    publishLocation: 'Container'
