apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssnapi
  labels:
    app: ssnapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssnapi
  template:
    metadata:
      labels:
        app: ssnapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      volumes:
        - name: ssnapi-storage
          persistentVolumeClaim:
            claimName: buildversionsapi-claim
      containers:
      - name: ssnapi
        image: registry:5000/ssnapi:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef: 
            name: ssnapi-secret
        - configMapRef:
            name: ssnapi-configmap
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            memory: "128Mi"
            cpu: "16m"
          limits:
            memory: "256Mi"
            cpu: "512m"
        volumeMounts:
          - mountPath: "/data"
            name: ssnapi-storage
---
