apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssnapi
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "ssnapi.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ssnapi
            port:
              number: 80
  - host: "ssnapi"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ssnapi
            port:
              number: 80
