apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testdemo
resources:
- configmap.yaml
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- secret.yaml
