apiVersion: v1
kind: PersistentVolumeClaim
#https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
metadata:
  name: testdemo-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
