apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ssnapi-secret
  namespace: ssnapi
spec:
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ssnapi-secret
      namespace: ssnapi

