apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: testdemo-secret
  namespace: testdemo
spec:
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: testdemo-secret
      namespace: testdemo

